export const news = [
  {
    id: "gxchvxc",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/1",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "gxchvxc",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/1",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "sdfsdfs",
    name: "Алексей Щербаков",
    title: "Рекруитер",
    image: "https://robohash.org/2",
    job: "Маркетолог",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "sgssd",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/3",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
];
export const current = [
  {
    id: "sffsgs",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/4",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "hwfscsd",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/5",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "jrtwfdfsd",
    name: "Алексей Щербаков",
    title: "Рекруитер",
    image: "https://robohash.org/6",
    job: "Маркетолог",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "fjnfhdv",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/7",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
];
export const archive = [
  {
    id: "sdfsdfsdf",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/8",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "wertgf",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/9",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "mjnbvcx",
    name: "Алексей Щербаков",
    title: "Рекруитер",
    image: "https://robohash.org/10",
    job: "Маркетолог",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "Второстепенная",
    clients: 3,
    docs: 123,
  },
  {
    id: "mlkjhgtfdrd",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/11",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "ertghgfdx",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/12",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
];
export const closed = [];
export const deleted = [
  {
    id: "kjfds",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/33",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "gxcdasdasdasdasdasdhvxc",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/44",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "sdfsddsafs",
    name: "Алексей Щербаков",
    title: "Рекруитер",
    image: "https://robohash.org/29",
    job: "Маркетолог",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
  {
    id: "sgssddskdasdasd",
    name: "John Doe",
    title: "Рекруитер",
    image: "https://robohash.org/32",
    job: "UI/UX дизайнер",
    jobTitle: "Отдел разработки мобильного приложения",
    status: "В приоритете",
    clients: 3,
    docs: 123,
  },
];
